server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadow_panel?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  dubbo:
    registry:
      address: zookeeper://localhost:2181
security:
  user:
    name: admin
    password: password
